apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: pull-request-approved
  namespace: tekton-test
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: pull-request-approved
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: pull-request-approved
  namespace: tekton-test
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "bitbucket"
      params:
        - name: "secretRef"
          value:
            secretName: bitbucket-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["pr:reviewer:approved", "pr:opened"]
  bindings:
    - ref: merge-after-change-validation
  template:
    ref: merge-after-change-validation
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: merge-after-change-validation
  namespace: tekton-test
spec:
  params:
  - name: bitbucket-branch-source
    value: $(body.pullRequest.fromRef.id)
  - name: bitbucket-branch-target
    value: $(body.pullRequest.toRef.id)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: merge-after-change-validation
  namespace: tekton-test
spec:
  params:
  - name: bitbucket-branch-source
    description: source branch
  - name: bitbucket-branch-target
    description: target branch

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: merge-after-change-validation-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: merge-after-change-validation
      params:
      - name: bitbucket-branch-source
        value: "$(tt.params.bitbucket-branch-source)"
      - name: bitbucket-branch-target
        value: "$(tt.params.bitbucket-branch-target)"
      workspaces:
        - name: shared-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-secret
  namespace: tekton-test
type: Opaque
stringData:
  secretToken: "1234567"

---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: source-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 500Mi