
apiVersion: v1
kind: Namespace
metadata:
  name: "tekton-test"
  labels:
    name: "tekton-test"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: merge-pr
  namespace: tekton-test
spec:
  params:
    - name: pr
      type: string
  steps:
    - args:
        - $(params.pr)
      command:
        - echo
      image: registry.redhat.io/ubi7/ubi-minimal
      name: merge-pr
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: servicenow-change-verify
  namespace: tekton-test
spec:
  params:
    - name: project-key
      description: project key
    - name: repository-slug
      description: Name of the repository
    - name: pull-request-id
      description: Pull request id
    - name: pull-request-version
      description: pull request current version
    - name: bitbucket-api-base-url
      description: bitbucket api base url     
    - name: pull-request-description
      description: pull request description           
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      name: print-change-ticket
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "Hello World!"
        echo $(params.project-key)
        TOKEN=${token}
        curl -v --request POST --url '$(params.bitbucket-api-base-url)rest/api/1.0/projects/$(params.project-key)/repos/$(params.repository-slug)/pull-requests/$(params.pull-request-id)/merge?version=$(params.pull-request-version)' --header 'Accept: application/json' --header "Authorization: Bearer $TOKEN" --header 'X-Atlassian-Token: no-check' -k
      env:
      - name: token
        valueFrom:
          secretKeyRef:
            name: bitbucket-token
            key: secretToken
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: merge-after-change-validation
  namespace: tekton-test
spec:
  params:
    - name: project-key
      description: project key
    - name: repository-slug
      description: Name of the repository
    - name: pull-request-id
      description: Pull request id
    - name: pull-request-version
      description: pull request current version
    - name: bitbucket-api-base-url
      description: bitbucket api base url
    - name: pull-request-description
      description: pull request description    
  tasks:
    - name: servicenow-change-verify
      params:
        - name: project-key
          value: "$(params.project-key)"
        - name: repository-slug
          value: "$(params.repository-slug)" 
        - name: pull-request-id
          value: "$(params.pull-request-id)"
        - name: pull-request-version
          value: "$(params.pull-request-version)" 
        - name: bitbucket-api-base-url
          value: "$(params.bitbucket-api-base-url)"
        - name: pull-request-description
          value: "$(params.pull-request-description)"                                      
      taskRef:
        kind: Task
        name: servicenow-change-verify

    - name: merge-pr
      params:
        - name: pr
          value: pr-merge-to-master
      runAfter:
        - servicenow-change-verify
      taskRef:
        kind: Task
        name: merge-pr

---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-token
  namespace: tekton-test
type: Opaque
stringData:
  secretToken: "xxxxxxxxx"